export {
  type Cadastro,
  type CadastroStatus,
  type CadastroInput,
  listarCadastros,
  buscarCadastro,
  buscarCadastroCompleto,
  deletarCadastro,
  criarCadastro,
  atualizarCadastro,
  aprovarCadastro,
  reprovarCadastro,
  solicitarCorrecao,
  STATUS_LABEL,
  STATUS_COLOR,
  getStatusOrder,
} from "~/features/clientes";
