export {
  type Documento,
  type DocumentoStatus,
  type DocStatus,
  getTipoLabel,
  STATUS_DOC_LABEL,
  STATUS_DOC_COLOR,
  uploadDocumento,
  listarDocumentos,
  aprovarDocumento,
  reprovarDocumento,
  solicitarCorrecaoDocumento,
  reverterDocumento,
  DOCS_PF_REQUIRED,
  DOCS_PJ_REQUIRED,
  DOC_STATUS_LABEL,
  DOC_STATUS_COLOR,
  determinarDocStatus,
  getDocumentosStatus,
  getDocumentosStatusMap,
  setDocumentosMassa,
} from "~/features/documentos";
