export {
  type Notificacao,
  type NotificacaoTemplate,
  listarNotificacoes,
  marcarComoLida,
  marcarTodasComoLidas,
  listarTemplates,
  criarTemplate,
  atualizarTemplate,
  atualizarTemplatePorId,
  deletarTemplate,
  enviarNotificacaoComTemplate,
  dispararNotificacaoIndividual,
  dispararNotificacoesInternas,
} from "~/core/services";
