import type { ColumnMapping, ImportType } from "../types"
import { IMPORT_FIELD_CONFIGS } from "../constants"

const COLUMN_SYNONYMS: Record<string, string[]> = {
  sku: ["sku", "codigo", "code", "item", "cod"],
  nome: ["nome", "name", "descricao", "description", "desc"],
  preco: ["preco", "price", "valor", "preço"],
  diametro_mm: ["diametro", "diameter", "dia", "ø"],
  comprimento_mm: ["comprimento", "length", "compr", "comp"],
  ativo: ["ativo", "active", "habilitado", "enabled"],
  categoria_nome: ["categoria", "category", "cat"],
  conexao_nome: ["conexao", "connection", "conn", "conexão"],
  familia_nome: ["familia", "family", "família"],
  linha_nome: ["linha", "line"],
  quantidade: ["quantidade", "qty", "quant", "qtd"],
  rosca_interna: ["rosca", "rosca interna", "thread"],
  venda_avulsa: ["venda avulsa", "avulso", "solto"],
  tipo_ferramenta: ["tipo ferramenta", "tipo", "tool type"],
  descricao: ["descricao", "description", "desc", "descrição"],
  angulacao_graus: ["angulacao", "angulation", "angulo", "angulação"],
  altura_transmucoso: ["altura transmucoso", "altura", "height"],
  diametro_plataforma: ["diametro plataforma", "plataforma", "platform"],
  tipo_reabilitacao_nome: ["tipo reabilitacao", "reabilitacao", "rehabilitation"],
  tipo_abutment_nome: ["tipo abutment", "abutment type"],
  categoria_kit_nome: ["categoria kit", "kit category"],
  familias: ["familias", "families", "famílias"],
  bom_tipo: ["bom tipo", "tipo item", "item type", "bom"],
  bom_sku: ["bom sku", "sku item", "item sku", "sku item bom"],
  bom_quantidade: ["bom quantidade", "bom qtd", "quantidade item", "qty"],
  workflow_nome: ["workflow", "protocolo", "protocol"],
  workflow_descricao: ["workflow descricao", "protocolo descricao", "workflow desc"],
  etapa_nome: ["etapa", "step", "fase", "stage"],
  etapa_ordem: ["etapa ordem", "ordem etapa", "step order", "ordem"],
  guia_familia_nome: ["guia familia", "familia guia", "guide family"],
  guia_tipo_abutment_nome: ["guia tipo abutment", "guia abutment"],
  guia_diametro: ["guia diametro", "diametro guia", "guide diameter"],
  guia_acessorio_sku: ["guia acessorio", "acessorio guia", "guide accessory"],
}

export function autoDetectMappings(
  fileHeaders: string[],
  importType: ImportType
): ColumnMapping[] {
  const fieldConfig = IMPORT_FIELD_CONFIGS[importType]
  if (!fieldConfig) return []

  return fieldConfig.targetFields.map((target) => {
    let matchedSource = fileHeaders.find(
      (h) => h.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "") ===
        target.key.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    )

    if (!matchedSource) {
      const synonyms = COLUMN_SYNONYMS[target.key] ?? []
      matchedSource = fileHeaders.find((h) => {
        const hLower = h.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")
        return synonyms.some((s) => hLower.includes(s))
      })
    }

    if (!matchedSource) {
      const keyBase = target.key.split("_")[0]
      matchedSource = fileHeaders.find((h) => {
        const hLower = h.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")
        return hLower.includes(keyBase.toLowerCase().slice(0, 4))
      })
    }

    return {
      sourceColumn: matchedSource ?? "",
      targetField: target.key,
      transform: target.transform as ColumnMapping["transform"],
      isRequired: target.required,
      isAutoGenerated: target.autoGenerated ?? false,
    }
  })
}

export function applyMapping(
  rawRows: Record<string, unknown>[],
  mappings: ColumnMapping[]
): Record<string, unknown>[] {
  return rawRows.map((row) => {
    const mapped: Record<string, unknown> = {}

    for (const m of mappings) {
      if (m.isAutoGenerated) continue
      const rawValue = m.sourceColumn ? row[m.sourceColumn] : null
      mapped[m.targetField] = transformValue(rawValue, m.transform)
    }

    return mapped
  })
}

function transformValue(value: unknown, transform?: ColumnMapping["transform"]): unknown {
  if (value === null || value === undefined || value === "") return null
  if (!transform) return value

  switch (transform.type) {
    case "number": {
      const n = Number(String(value).replace(",", "."))
      return isNaN(n) ? null : n
    }
    case "boolean": {
      const s = String(value).toLowerCase()
      return ["true", "sim", "1", "yes", "s"].includes(s)
    }
    case "date":
      return value
    case "enum": {
      const normalized = String(value).trim().toLowerCase()
      return transform.values?.find((v) => v.toLowerCase() === normalized) ?? null
    }
    default:
      return value
  }
}

export function getTransformPreview(
  value: unknown,
  transform?: ColumnMapping["transform"]
): string {
  if (value === null || value === undefined || value === "") return "—"
  const transformed = transformValue(value, transform)
  if (transformed === null) return "(invalido)"
  return String(transformed)
}
