import type { ImportType } from "./types"
import type { BOMItemTipo } from "../types"

export interface TargetFieldConfig {
  key: string
  label: string
  required: boolean
  type: "string" | "number" | "boolean"
  transform?: { type: string; values?: string[] }
  autoGenerated?: boolean
  example: string
}

export interface ImportTypeConfig {
  label: string
  description: string
  icon: string
  templateHeaders: { key: string; label: string; required: boolean; example: string }[]
  targetFields: TargetFieldConfig[]
  dependencies: ImportType[]
  supabaseTable: string
}

export const IMPORT_FIELD_CONFIGS: Record<ImportType, ImportTypeConfig> = {
  hierarquia: {
    label: "Hierarquia",
    description: "Categorias, Conexoes, Familias e Linhas",
    icon: "Network",
    templateHeaders: [
      { key: "categoria", label: "Categoria", required: true, example: "Implante" },
      { key: "conexao", label: "Conexao", required: true, example: "Conical" },
      { key: "conexao_sigla", label: "Sigla Conexao", required: false, example: "CON" },
      { key: "familia", label: "Familia", required: true, example: "Tornillo" },
      { key: "familia_cor", label: "Cor Familia", required: false, example: "#FF5733" },
      { key: "linha", label: "Linha", required: true, example: "Standard" },
    ],
    targetFields: [
      { key: "categoria_nome", label: "Categoria", required: true, type: "string", example: "Implante" },
      { key: "conexao_nome", label: "Conexao", required: true, type: "string", example: "Conical" },
      { key: "conexao_sigla", label: "Sigla", required: false, type: "string", example: "CON" },
      { key: "familia_nome", label: "Familia", required: true, type: "string", example: "Tornillo" },
      { key: "familia_cor", label: "Cor", required: false, type: "string", example: "#FF5733" },
      { key: "linha_nome", label: "Linha", required: true, type: "string", example: "Standard" },
    ],
    dependencies: [],
    supabaseTable: "catalogo_categorias",
  },

  implantes: {
    label: "Implantes",
    description: "SKUs de implantes com dimensoes e preco",
    icon: "CircleDot",
    templateHeaders: [
      { key: "sku", label: "SKU", required: true, example: "IMP-CON-TOR-001" },
      { key: "categoria", label: "Categoria", required: true, example: "Implante" },
      { key: "conexao", label: "Conexao", required: true, example: "Conical" },
      { key: "familia", label: "Familia", required: true, example: "Tornillo" },
      { key: "linha", label: "Linha", required: true, example: "Standard" },
      { key: "diametro_mm", label: "Diametro (mm)", required: true, example: "4.0" },
      { key: "comprimento_mm", label: "Comprimento (mm)", required: true, example: "10" },
      { key: "preco", label: "Preco", required: true, example: "189.90" },
      { key: "rosca_interna", label: "Rosca Interna", required: false, example: "Hex" },
      { key: "ativo", label: "Ativo", required: false, example: "sim" },
    ],
    targetFields: [
      { key: "sku", label: "SKU", required: true, type: "string", example: "IMP-CON-TOR-001" },
      { key: "categoria_nome", label: "Categoria", required: true, type: "string", example: "Implante" },
      { key: "conexao_nome", label: "Conexao", required: true, type: "string", example: "Conical" },
      { key: "familia_nome", label: "Familia", required: true, type: "string", example: "Tornillo" },
      { key: "linha_nome", label: "Linha", required: true, type: "string", example: "Standard" },
      { key: "diametro_mm", label: "Diametro", required: true, type: "number", transform: { type: "number" }, example: "4.0" },
      { key: "comprimento_mm", label: "Comprimento", required: true, type: "number", transform: { type: "number" }, example: "10" },
      { key: "preco", label: "Preco", required: true, type: "number", transform: { type: "number" }, example: "189.90" },
      { key: "rosca_interna", label: "Rosca Interna", required: false, type: "string", example: "Hex" },
      { key: "ativo", label: "Ativo", required: false, type: "boolean", transform: { type: "boolean" }, example: "sim" },
    ],
    dependencies: ["hierarquia"],
    supabaseTable: "catalogo_implantes",
  },

  abutments: {
    label: "Abutments",
    description: "Abutments com tipos de reabilitacao",
    icon: "Component",
    templateHeaders: [
      { key: "sku", label: "SKU", required: true, example: "ABT-001" },
      { key: "familia", label: "Familia", required: true, example: "Tornillo" },
      { key: "tipo_reabilitacao", label: "Tipo Reabilitacao", required: true, example: "Unitaria" },
      { key: "tipo_abutment", label: "Tipo Abutment", required: true, example: "MU" },
      { key: "diametro_plataforma", label: "Diametro Plataforma", required: false, example: "3.5" },
      { key: "angulacao_graus", label: "Angulacao (graus)", required: false, example: "15" },
      { key: "altura_transmucoso", label: "Altura Transmucoso", required: false, example: "2.0" },
      { key: "preco", label: "Preco", required: true, example: "250.00" },
      { key: "ativo", label: "Ativo", required: false, example: "sim" },
    ],
    targetFields: [
      { key: "sku", label: "SKU", required: true, type: "string", example: "ABT-001" },
      { key: "familia_nome", label: "Familia", required: true, type: "string", example: "Tornillo" },
      { key: "tipo_reabilitacao_nome", label: "Tipo Reabilitacao", required: true, type: "string", example: "Unitaria" },
      { key: "tipo_abutment_nome", label: "Tipo Abutment", required: true, type: "string", example: "MU" },
      { key: "diametro_plataforma", label: "Diametro Plataforma", required: false, type: "string", example: "3.5" },
      { key: "angulacao_graus", label: "Angulacao", required: false, type: "number", transform: { type: "number" }, example: "15" },
      { key: "altura_transmucoso", label: "Altura Transmucoso", required: false, type: "number", transform: { type: "number" }, example: "2.0" },
      { key: "preco", label: "Preco", required: true, type: "number", transform: { type: "number" }, example: "250.00" },
      { key: "ativo", label: "Ativo", required: false, type: "boolean", transform: { type: "boolean" }, example: "sim" },
    ],
    dependencies: ["hierarquia"],
    supabaseTable: "catalogo_abutments",
  },

  fresas: {
    label: "Fresas",
    description: "Fresas (independentes)",
    icon: "Disc",
    templateHeaders: [
      { key: "sku", label: "SKU", required: true, example: "FRE-001" },
      { key: "nome", label: "Nome", required: true, example: "Fresa Paralela 2.3" },
      { key: "diametro_mm", label: "Diametro (mm)", required: false, example: "2.3" },
      { key: "preco", label: "Preco", required: true, example: "89.90" },
      { key: "venda_avulsa", label: "Venda Avulsa", required: false, example: "sim" },
      { key: "ativo", label: "Ativo", required: false, example: "sim" },
    ],
    targetFields: [
      { key: "sku", label: "SKU", required: true, type: "string", example: "FRE-001" },
      { key: "nome", label: "Nome", required: true, type: "string", example: "Fresa Paralela 2.3" },
      { key: "diametro_mm", label: "Diametro", required: false, type: "number", transform: { type: "number" }, example: "2.3" },
      { key: "preco", label: "Preco", required: true, type: "number", transform: { type: "number" }, example: "89.90" },
      { key: "venda_avulsa", label: "Venda Avulsa", required: false, type: "boolean", transform: { type: "boolean" }, example: "sim" },
      { key: "ativo", label: "Ativo", required: false, type: "boolean", transform: { type: "boolean" }, example: "sim" },
    ],
    dependencies: [],
    supabaseTable: "catalogo_fresas",
  },

  acessorios: {
    label: "Acessorios",
    description: "Acessorios por categoria",
    icon: "Package",
    templateHeaders: [
      { key: "sku", label: "SKU", required: true, example: "ACE-001" },
      { key: "categoria", label: "Categoria", required: true, example: "Cicatrizador" },
      { key: "nome", label: "Nome", required: true, example: "Cicatrizador Ti 4.0" },
      { key: "diametro_mm", label: "Diametro (mm)", required: false, example: "4.0" },
      { key: "preco", label: "Preco", required: true, example: "120.00" },
      { key: "ativo", label: "Ativo", required: false, example: "sim" },
    ],
    targetFields: [
      { key: "sku", label: "SKU", required: true, type: "string", example: "ACE-001" },
      { key: "categoria_nome", label: "Categoria", required: true, type: "string", example: "Cicatrizador" },
      { key: "nome", label: "Nome", required: true, type: "string", example: "Cicatrizador Ti 4.0" },
      { key: "diametro_mm", label: "Diametro", required: false, type: "number", transform: { type: "number" }, example: "4.0" },
      { key: "preco", label: "Preco", required: true, type: "number", transform: { type: "number" }, example: "120.00" },
      { key: "ativo", label: "Ativo", required: false, type: "boolean", transform: { type: "boolean" }, example: "sim" },
    ],
    dependencies: [],
    supabaseTable: "catalogo_acessorios",
  },

  chaves: {
    label: "Chaves Ferramentais",
    description: "Chaves ferramentais",
    icon: "Wrench",
    templateHeaders: [
      { key: "sku", label: "SKU", required: true, example: "CHA-001" },
      { key: "nome", label: "Nome", required: true, example: "Chave de Aperto Torque" },
      { key: "tipo_ferramenta", label: "Tipo Ferramenta", required: true, example: "Aperto" },
      { key: "preco", label: "Preco", required: true, example: "350.00" },
      { key: "ativo", label: "Ativo", required: false, example: "sim" },
    ],
    targetFields: [
      { key: "sku", label: "SKU", required: true, type: "string", example: "CHA-001" },
      { key: "nome", label: "Nome", required: true, type: "string", example: "Chave de Aperto Torque" },
      { key: "tipo_ferramenta", label: "Tipo Ferramenta", required: true, type: "string", transform: { type: "enum", values: ["Aperto", "Medicao", "Cirurgica"] }, example: "Aperto" },
      { key: "preco", label: "Preco", required: true, type: "number", transform: { type: "number" }, example: "350.00" },
      { key: "ativo", label: "Ativo", required: false, type: "boolean", transform: { type: "boolean" }, example: "sim" },
    ],
    dependencies: [],
    supabaseTable: "catalogo_chaves_ferramental",
  },

  instrumentais: {
    label: "Instrumentais",
    description: "Instrumentais gerais por categoria",
    icon: "Scissors",
    templateHeaders: [
      { key: "sku", label: "SKU", required: true, example: "INS-001" },
      { key: "categoria", label: "Categoria", required: true, example: "Cirurgico" },
      { key: "nome", label: "Nome", required: true, example: "Kit Instrumental Basico" },
      { key: "preco", label: "Preco", required: true, example: "1200.00" },
      { key: "ativo", label: "Ativo", required: false, example: "sim" },
    ],
    targetFields: [
      { key: "sku", label: "SKU", required: true, type: "string", example: "INS-001" },
      { key: "categoria_nome", label: "Categoria", required: true, type: "string", example: "Cirurgico" },
      { key: "nome", label: "Nome", required: true, type: "string", example: "Kit Instrumental Basico" },
      { key: "preco", label: "Preco", required: true, type: "number", transform: { type: "number" }, example: "1200.00" },
      { key: "ativo", label: "Ativo", required: false, type: "boolean", transform: { type: "boolean" }, example: "sim" },
    ],
    dependencies: [],
    supabaseTable: "catalogo_instrumentais_gerais",
  },

  kits: {
    label: "Kits",
    description: "Kits com composicao BOM e familias",
    icon: "Boxes",
    templateHeaders: [
      { key: "sku", label: "SKU Kit", required: true, example: "KIT-001" },
      { key: "nome", label: "Nome", required: true, example: "Kit Inicial Tornillo" },
      { key: "descricao", label: "Descricao", required: false, example: "Kit completo para cirurgia" },
      { key: "categoria_kit", label: "Categoria Kit", required: true, example: "Cirurgia" },
      { key: "preco", label: "Preco", required: true, example: "2500.00" },
      { key: "familias", label: "Familias (separar por ;)", required: false, example: "Tornillo;Hex" },
      { key: "bom_tipo", label: "BOM: Tipo Item", required: false, example: "implante" },
      { key: "bom_sku", label: "BOM: SKU Item", required: false, example: "IMP-CON-TOR-001" },
      { key: "bom_quantidade", label: "BOM: Quantidade", required: false, example: "2" },
    ],
    targetFields: [
      { key: "sku", label: "SKU Kit", required: true, type: "string", example: "KIT-001" },
      { key: "nome", label: "Nome", required: true, type: "string", example: "Kit Inicial Tornillo" },
      { key: "descricao", label: "Descricao", required: false, type: "string", example: "Kit completo" },
      { key: "categoria_kit_nome", label: "Categoria Kit", required: true, type: "string", example: "Cirurgia" },
      { key: "preco", label: "Preco", required: true, type: "number", transform: { type: "number" }, example: "2500.00" },
      { key: "familias", label: "Familias", required: false, type: "string", example: "Tornillo;Hex" },
      { key: "bom_tipo", label: "BOM Tipo", required: false, type: "string", transform: { type: "enum", values: ["fresa", "chave", "acessorio", "instrumental", "implante"] }, example: "implante" },
      { key: "bom_sku", label: "BOM SKU", required: false, type: "string", example: "IMP-CON-TOR-001" },
      { key: "bom_quantidade", label: "BOM Qtd", required: false, type: "number", transform: { type: "number" }, example: "2" },
    ],
    dependencies: ["hierarquia"],
    supabaseTable: "catalogo_kits",
  },

  workflows: {
    label: "Workflows",
    description: "Workflows, etapas e guias de reabilitacao",
    icon: "GitBranch",
    templateHeaders: [
      { key: "workflow_nome", label: "Workflow", required: true, example: "Reabilitacao Superior" },
      { key: "workflow_descricao", label: "Descricao", required: false, example: "Protocolo completo" },
      { key: "etapa_nome", label: "Etapa", required: true, example: "Impressao" },
      { key: "etapa_ordem", label: "Ordem Etapa", required: true, example: "1" },
      { key: "guia_familia", label: "Guia: Familia", required: false, example: "Tornillo" },
      { key: "guia_tipo_abutment", label: "Guia: Tipo Abutment", required: false, example: "MU" },
      { key: "guia_diametro", label: "Guia: Diametro", required: false, example: "4.0" },
      { key: "guia_acessorio_sku", label: "Guia: Acessorio SKU", required: false, example: "ACE-001" },
    ],
    targetFields: [
      { key: "workflow_nome", label: "Workflow", required: true, type: "string", example: "Reabilitacao Superior" },
      { key: "workflow_descricao", label: "Descricao", required: false, type: "string", example: "Protocolo completo" },
      { key: "etapa_nome", label: "Etapa", required: true, type: "string", example: "Impressao" },
      { key: "etapa_ordem", label: "Ordem", required: true, type: "number", transform: { type: "number" }, example: "1" },
      { key: "guia_familia_nome", label: "Familia", required: false, type: "string", example: "Tornillo" },
      { key: "guia_tipo_abutment_nome", label: "Tipo Abutment", required: false, type: "string", example: "MU" },
      { key: "guia_diametro", label: "Diametro", required: false, type: "number", transform: { type: "number" }, example: "4.0" },
      { key: "guia_acessorio_sku", label: "SKU Acessorio", required: false, type: "string", example: "ACE-001" },
    ],
    dependencies: ["hierarquia"],
    supabaseTable: "catalogo_workflows",
  },
}

export const IMPORT_TYPE_LABELS: Record<ImportType, string> = {
  hierarquia: "Hierarquia",
  implantes: "Implantes",
  abutments: "Abutments",
  fresas: "Fresas",
  acessorios: "Acessorios",
  chaves: "Chaves",
  instrumentais: "Instrumentais",
  kits: "Kits",
  workflows: "Workflows",
}

export const BOM_ITEM_TIPOS: BOMItemTipo[] = ["fresa", "chave", "acessorio", "instrumental", "implante"]

export const BOM_FK_MAP: Record<BOMItemTipo, string> = {
  fresa: "fresa_sku",
  chave: "chave_sku",
  acessorio: "acessorio_sku",
  instrumental: "instrumental_sku",
  implante: "implante_sku",
}
